### ISSUE TITLE
How to upload my own data ?

### ISSUE THREAD

**Issue by tarunparmar** [davesteps/machLearn#2]
Firstly , kudos for a great app. Works like a charm for inbuilt datasets and all the outputs are very presentable.

I tried to upload my own dataset but the app doesnt respond to it. I noticed you have it disabled using shinyjs package but it is not enabled again. Not sure if that is something you are still working on. Or if I missed something.

Thanks again for sharing such an awesome app.

**Comment by tarunparmar** [comment]
I didnt know I had to be logged in at beerpay, my donation went as anonymous. 😜

**Comment by davesteps** [comment]
Hi Tarun,
Firstly, many thanks for the donation! It has been some time since I have had chance to work on this.   I have been meaning to refresh this app at some point and if I have chance in the coming weeks I'll dive back into it. 

I seem to remember that I disabled the upload button becuase it is running on my shinyapps.io which is quite small I usually run out of allocated bandwidth by the end of the month! If you wanted to use it on your own data you could clone the repo and run it locally, then it should be a case of enabling the upload button. 

If you do run it locally you may have one or two issues with package versions since I expect most of the packages used will have been updated since.

Let me know how you get on, I will try and help with any issues. 

Cheers!

**Comment by tarunparmar** [comment]
Thanks for your reply Dave. 
I did try to fiddle and comment `disabled()` but doesnt seem to do the trick.
I also then tried to add a simple if-else to choose rawdata() based on whether user had something uploaded 
```
  rawdata <- reactive({
    if(is.null(input$fileIn) || input$fileIn == ""){
      datasets[[input$dataset]]
      } else {
        input$fileIn %>% as.data.frame()
      }
  })

```

but it errored for this: 
```
Warning: Error in createDataPartition: y must have at least 2 data points
Stack trace (innermost first):
    57: createDataPartition
    56: observerFunc [C:\Users\tparmar\Downloads\machLearn-master/app.R#84]
     1: runApp
ERROR: [on_request_read] connection reset by peer
```
The code at line 84 is this:
```
    trainIndex <- createDataPartition(df2$y,
                                      p = 1-(testsize/100),
                                      list = FALSE,
                                      times = 1)

```

**Comment by tarunparmar** [comment]
Was missing a couple things , had to add `datapath` to `input$fileIn$datapath` for it to read the file with `read.csv`. 

But still facing this error :
`Error in createDataPartition: y must have at least 2 data points` 

It seems for some reason it is having difficulty reading the file. So I am going to try adding some more formats to see if that solves it. 

The above error was for titanic dataset which has some columns with column values that are comma separated. 

Oh btw, if you are interested in adding the upload feature to your shinyapps.io app then may be you can try limiting upload size by this statement. You probably know about it already I guess :wink: 

This would limit the upload to 30MB:
`options(shiny.maxRequestSize=30*1024^2)`

**Comment by corridordigital** [comment]
Hey guys, 

  First, a big Bravo for the great work on this app Davesteps, it is clearly the most beautiful use of Shiny I've ever seen. Just like you Tarunpamar, I am playing with it in order to create a fork to demonstrate an automated ML workflow with a small uploaded dataset. 
The upload feature indeed isn't working out of the box and I get the  : 

```
Warning: Error in createDataPartition: y must have at least 2 data points
```
Which is a caret error meaning the object passed to the `y` argument of `trainIndex <- createDataPartition()` is not in the right format (must be a vector).
Even by forcing the format of `df2$y` with the `as.vector()` function, the issue is not solved. The issue seems to be caused by the upload process server.R side. 

Looking for a solution ! :)

**Comment by tarunparmar** [comment]
I was battling this error for past few days, appears it's due to Null/NA
values in the dataset. With one of my datasets the complete.cases()
function was returning 0 rows which is why createdataPartition() was
failing.

**Comment by gbbunevich** [comment]
@tarunparmar did you get your own dataset successfully uploaded? The app says that my data was uploaded however it doesn't show up in the app as an option to train it...

**Comment by tarunparmar** [comment]
@gbbunevich if you refer the comments above after Dave's response you may be able to figure out how to enable it. I had to make those changes for it to work.

![image](https://user-images.githubusercontent.com/17690950/33343784-93224048-d454-11e7-93bc-6ffa0869b239.png)

**Comment by gbbunevich** [comment]
@tarunparmar 
Looks like that your app is running well.  However, my app doesn't  upload the data succesfully like yours... and I don't have any null/NA value in my CSV file.
I really don't know what I am missing, I did exactly this:
First, I commented the #disable() function (line 601)

Then as you said above, I altered this part of the code to:

```
rawdata <- reactive({
    if(is.null(input$fileIn$datapath) || input$fileIn$datapath == ""){
      datasets[[input$dataset]]
    } else {
    
      input$fileIn$datapath %>% as.data.frame()
    
    }
  })

```
However the app doesn't work. Am I missing something?

Sorry, I am new to R language.
